### ISSUE TITLE
User Story - Navbar

### ISSUE THREAD

**Issue by EfthymiaKakoulidou** [EfthymiaKakoulidou/starathon#12]
As a **user** I would like **to have a clear navigation bar** so that **I can have access to all the sections of the app**

**Acceptance Criteria**
-Navbar visible on all the different pages
-Navbar items : Home, About, Game ... 
-Active state
-Hover

**Tasks**
-Create the navbar based on **https://codemyui.com/star-wars-lightsaber-hamburger-menu-icon/**

**Comment by VCGithubCode** [comment]
Done and looks pretty good, may be refined later as other ideas become available
