### ISSUE TITLE
Overlapping with context text and menu for small screen sizes

### ISSUE THREAD

**Issue by Zest-studi-o** [EfthymiaKakoulidou/starathon#130]
**Describe the bug**
The main menu and some page content is overlapping

**To Reproduce**
1. Go to 'main page'
2. Click on 'quiz'
3. Finish the quiz and click on the burger menu
4. Observe the issue with the overlap

**Actual behavior**
The menu and text content overlaps a bit and gets a bit difficult to read

**Expected behavior**
The menu and text content should not cause any visual issues

**Screenshots**
<img width="354" alt="Captura de pantalla 2024-05-26 a las 10 17 20" src="https://github.com/EfthymiaKakoulidou/starathon/assets/83344172/6cce482d-d4b5-4177-bfbc-87deff117228">

**Smartphone:**
 - Device: [Galaxy S8]
 - OS: [Android]
 - Browser [Chrome]
---
 - Device: [OnePlus 7T]
 - OS: [Android]
 - Browser [Chrome]

**Comment by VCGithubCode** [comment]
Made background opaque now no text can be seen inside
