### ISSUE TITLE
Add various star wars sounds for user interactions and gameplay.

### ISSUE THREAD

**Issue by Joao4569** [EfthymiaKakoulidou/starathon#73]
As a **User** I would like **to have Star Wars sound effects in the game** so that **I can have an immersive experience**

**Acceptance Criteria**
- [x] At least one Star Wars sound effect is in the final game as per hackathon requirements.

**Tasks**
- [x] Add Star Wars sound effects where appropriate in game.

**Comment by VCGithubCode** [comment]
I added the sounds folder and 12 sound effects to use for testing and application as the team sees fit
